# Generated by Django 3.1.5 on 2021-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_auto_20210222_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sell',
            name='discounttypes',
            field=models.CharField(choices=[('flat', 'flat'), ('percent', 'percent')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='sprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buy',
            name='bquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buy',
            name='brate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sell',
            name='squantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sell',
            name='srate',
            field=models.IntegerField(default=0),
        ),
    ]
