# Generated by Django 3.1.5 on 2021-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_auto_20210227_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='discounttypes',
        ),
        migrations.AddField(
            model_name='sell',
            name='discounttype',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
