# Generated by Django 3.1.5 on 2021-03-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_producttype_hsncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='hsncode',
        ),
    ]
