# Generated by Django 3.1.5 on 2021-03-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_remove_producttype_hsncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='hsncode',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
